In [8]:

import tensorflow as tf # pip install tensorflow --upgrade
import tensorflow_datasets as tfds  # pip install tensorflow_datasets
import tensorflow_hub as hub  #pip install tensorflow_hub

## TENSORFLOW HUB
TensorFlow Hub is a library for the publication, discovery, and consumption of reusable parts of machine learning models. A module is a self-contained piece of a TensorFlow graph, along with its weights and assets, that can be reused across different tasks in a process known as transfer learning. Transfer learning can:
   
   -Train a model with a smaller dataset,
   
   -Improve generalization, and
   
   -Speed up training.

In [9]:
tf.__version__

'2.0.0'

In [22]:
tfds.list_builders()  # IN TENSORFLOW HAVING  MANY DATASETS BUT WE ARE USING IMBD_REVIEWS DATASETS.

['abstract_reasoning',
 'aeslc',
 'aflw2k3d',
 'amazon_us_reviews',
 'bair_robot_pushing_small',
 'big_patent',
 'bigearthnet',
 'billsum',
 'binarized_mnist',
 'binary_alpha_digits',
 'c4',
 'caltech101',
 'caltech_birds2010',
 'caltech_birds2011',
 'cars196',
 'cassava',
 'cats_vs_dogs',
 'celeb_a',
 'celeb_a_hq',
 'chexpert',
 'cifar10',
 'cifar100',
 'cifar10_1',
 'cifar10_corrupted',
 'clevr',
 'cmaterdb',
 'cnn_dailymail',
 'coco',
 'coco2014',
 'coil100',
 'colorectal_histology',
 'colorectal_histology_large',
 'curated_breast_imaging_ddsm',
 'cycle_gan',
 'deep_weeds',
 'definite_pronoun_resolution',
 'diabetic_retinopathy_detection',
 'downsampled_imagenet',
 'dsprites',
 'dtd',
 'dummy_dataset_shared_generator',
 'dummy_mnist',
 'emnist',
 'eurosat',
 'fashion_mnist',
 'flores',
 'food101',
 'gap',
 'gigaword',
 'glue',
 'groove',
 'higgs',
 'horses_or_humans',
 'image_label_folder',
 'imagenet2012',
 'imagenet2012_corrupted',
 'imagenet_resized',
 'imdb_reviews',
 'iris',
 '

## ABOUT TRAINING DATA, VALIDATION DATA AND TESTING DATA
When a large amount of data is at hand, a set of samples can be set aside to evaluate the final model. The “training” data set is the general term for the samples used to create the model, while the “test” or “validation” data set is used to qualify performance.


A validation dataset is a sample of data held back from training your model that is used to give an estimate of model skill while tuning model’s hyperparameters.


The validation dataset is different from the test dataset that is also held back from the training of the model, but is instead used to give an unbiased estimate of the skill of the final tuned model when comparing or selecting between final models.


There is much confusion in applied machine learning about what a validation dataset is exactly and how it differs from a test dataset.

In [11]:
(train_data, validation_data), test_data = tfds.load(name='imdb_reviews',
         split=(tfds.Split.TRAIN.subsplit([6,4]),tfds.Split.TEST),       
         as_supervised=True)                      

     #split=(tfds.Split.TRAIN.subsplit([6,4]) MEANS SPLITING DATA INTO TRAINING(60) AND TESTING(40) DATA  

Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`


Instructions for updating:
Use eager execution and: 
`tf.data.TFRecordDataset(path)`


Dataset imdb_reviews downloaded and prepared to C:\Users\ABHI\tensorflow_datasets\imdb_reviews\plain_text\0.1.0. Subsequent calls will reuse this data.


In [12]:
train_examples_batch, train_labels_batch = next(iter(train_data.batch(10)))
train_examples_batch

<tf.Tensor: id=219, shape=(10,), dtype=string, numpy=
array([b"As a lifelong fan of Dickens, I have invariably been disappointed by adaptations of his novels.<br /><br />Although his works presented an extremely accurate re-telling of human life at every level in Victorian Britain, throughout them all was a pervasive thread of humour that could be both playful or sarcastic as the narrative dictated. In a way, he was a literary caricaturist and cartoonist. He could be serious and hilarious in the same sentence. He pricked pride, lampooned arrogance, celebrated modesty, and empathised with loneliness and poverty. It may be a clich\xc3\xa9, but he was a people's writer.<br /><br />And it is the comedy that is so often missing from his interpretations. At the time of writing, Oliver Twist is being dramatised in serial form on BBC television. All of the misery and cruelty is their, but non of the humour, irony, and savage lampoonery. The result is just a dark, dismal experience: the story p

In [13]:
train_labels_batch

<tf.Tensor: id=220, shape=(10,), dtype=int64, numpy=array([1, 1, 1, 1, 1, 1, 0, 1, 1, 0], dtype=int64)>

In [14]:
pretrained_model = "https://tfhub.dev/google/tf2-preview/gnews-swivel-20dim/1"
hub_layer = hub.KerasLayer(pretrained_model, input_shape=[], dtype=tf.string, trainable=True)

In [15]:
hub_layer(train_examples_batch[:2])

<tf.Tensor: id=400, shape=(2, 20), dtype=float32, numpy=
array([[ 3.9819887 , -4.4838037 ,  5.177359  , -2.3643482 , -3.2938678 ,
        -3.5364532 , -2.4786978 ,  2.5525482 ,  6.688532  , -2.3076782 ,
        -1.9807833 ,  1.1315885 , -3.0339816 , -0.7604128 , -5.743445  ,
         3.4242578 ,  4.790099  , -4.03061   , -5.992149  , -1.7297493 ],
       [ 3.4232912 , -4.230874  ,  4.1488533 , -0.29553518, -6.802391  ,
        -2.5163853 , -4.4002395 ,  1.905792  ,  4.7512794 , -0.40538004,
        -4.3401685 ,  1.0361497 ,  0.9744097 ,  0.71507156, -6.2657013 ,
         0.16533905,  4.560262  , -1.3106939 , -3.1121316 , -2.1338716 ]],
      dtype=float32)>

In [16]:
train_examples_batch[:2]

<tf.Tensor: id=404, shape=(2,), dtype=string, numpy=
array([b"As a lifelong fan of Dickens, I have invariably been disappointed by adaptations of his novels.<br /><br />Although his works presented an extremely accurate re-telling of human life at every level in Victorian Britain, throughout them all was a pervasive thread of humour that could be both playful or sarcastic as the narrative dictated. In a way, he was a literary caricaturist and cartoonist. He could be serious and hilarious in the same sentence. He pricked pride, lampooned arrogance, celebrated modesty, and empathised with loneliness and poverty. It may be a clich\xc3\xa9, but he was a people's writer.<br /><br />And it is the comedy that is so often missing from his interpretations. At the time of writing, Oliver Twist is being dramatised in serial form on BBC television. All of the misery and cruelty is their, but non of the humour, irony, and savage lampoonery. The result is just a dark, dismal experience: the story pe

In [17]:
model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16,activation="relu"))
model.add(tf.keras.layers.Dense(1,activation="sigmoid"))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
keras_layer (KerasLayer)     (None, 20)                400020    
_________________________________________________________________
dense (Dense)                (None, 16)                336       
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 17        
Total params: 400,373
Trainable params: 400,373
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [19]:
model.fit(train_data.shuffle(10000).batch(512),
         epochs=20,
         validation_data=validation_data.batch(512),
         verbose=1)

Epoch 1/20
30/30 [==============================].9071 - accuracy: 0.46 - 2s 875ms/step - loss: 0.9341 - accuracy: 0.440 - 2s 623ms/step - loss: 0.9286 - accuracy: 0.438 - 2s 498ms/step - loss: 0.9050 - accuracy: 0.436 - 2s 420ms/step - loss: 0.8955 - accuracy: 0.438 - 2s 367ms/step - loss: 0.8895 - accuracy: 0.440 - 2s 331ms/step - loss: 0.8805 - accuracy: 0.439 - 2s 303ms/step - loss: 0.8756 - accuracy: 0.440 - 3s 283ms/step - loss: 0.8677 - accuracy: 0.446 - 3s 263ms/step - loss: 0.8628 - accuracy: 0.447 - 3s 246ms/step - loss: 0.8560 - accuracy: 0.451 - 3s 232ms/step - loss: 0.8499 - accuracy: 0.454 - 3s 221ms/step - loss: 0.8426 - accuracy: 0.457 - 3s 211ms/step - loss: 0.8369 - accuracy: 0.459 - 3s 203ms/step - loss: 0.8300 - accuracy: 0.463 - 3s 195ms/step - loss: 0.8243 - accuracy: 0.469 - 3s 188ms/step - loss: 0.8213 - accuracy: 0.471 - 3s 182ms/step - loss: 0.8167 - accuracy: 0.473 - 3s 177ms/step - loss: 0.8113 - accuracy: 0.477 - 3s 172ms/step - loss: 0.8071 - accuracy: 0.4

Epoch 9/20
30/30 [==============================] - ETA: 18s - loss: 0.3980 - accuracy: 0.841 - ETA: 9s - loss: 0.4064 - accuracy: 0.830 - ETA: 6s - loss: 0.4044 - accuracy: 0.83 - ETA: 5s - loss: 0.3963 - accuracy: 0.83 - ETA: 4s - loss: 0.3938 - accuracy: 0.84 - ETA: 3s - loss: 0.3940 - accuracy: 0.83 - ETA: 3s - loss: 0.3931 - accuracy: 0.83 - ETA: 2s - loss: 0.3911 - accuracy: 0.84 - ETA: 2s - loss: 0.3905 - accuracy: 0.84 - ETA: 1s - loss: 0.3903 - accuracy: 0.84 - ETA: 1s - loss: 0.3872 - accuracy: 0.84 - ETA: 1s - loss: 0.3866 - accuracy: 0.84 - ETA: 1s - loss: 0.3866 - accuracy: 0.84 - ETA: 0s - loss: 0.3850 - accuracy: 0.84 - ETA: 0s - loss: 0.3838 - accuracy: 0.84 - ETA: 0s - loss: 0.3839 - accuracy: 0.84 - ETA: 0s - loss: 0.3831 - accuracy: 0.84 - ETA: 0s - loss: 0.3832 - accuracy: 0.84 - ETA: 0s - loss: 0.3829 - accuracy: 0.84 - 5s 176ms/step - loss: 0.3832 - accuracy: 0.8433 - val_loss: 0.3997 - val_accuracy: 0.8263
Epoch 10/20
30/30 [==============================] - ETA:

30/30 [==============================] - ETA: 15s - loss: 0.2358 - accuracy: 0.925 - ETA: 8s - loss: 0.2324 - accuracy: 0.918 - ETA: 5s - loss: 0.2335 - accuracy: 0.91 - ETA: 4s - loss: 0.2331 - accuracy: 0.91 - ETA: 3s - loss: 0.2354 - accuracy: 0.91 - ETA: 3s - loss: 0.2301 - accuracy: 0.91 - ETA: 2s - loss: 0.2276 - accuracy: 0.91 - ETA: 2s - loss: 0.2257 - accuracy: 0.91 - ETA: 2s - loss: 0.2268 - accuracy: 0.91 - ETA: 1s - loss: 0.2268 - accuracy: 0.91 - ETA: 1s - loss: 0.2270 - accuracy: 0.91 - ETA: 1s - loss: 0.2258 - accuracy: 0.91 - ETA: 1s - loss: 0.2240 - accuracy: 0.91 - ETA: 0s - loss: 0.2249 - accuracy: 0.91 - ETA: 0s - loss: 0.2265 - accuracy: 0.91 - ETA: 0s - loss: 0.2264 - accuracy: 0.91 - ETA: 0s - loss: 0.2249 - accuracy: 0.91 - ETA: 0s - loss: 0.2250 - accuracy: 0.91 - ETA: 0s - loss: 0.2262 - accuracy: 0.91 - 6s 207ms/step - loss: 0.2250 - accuracy: 0.9208 - val_loss: 0.3069 - val_accuracy: 0.8716
Epoch 18/20
30/30 [==============================] - ETA: 20s - loss

In [20]:
model.predict(["This is the worst movie I have ever seen",
              "An excellent movie that I enjoyed a lot",
              "how can one make such a horrible movie? there is no story, acting direction everything is very poor"])

array([[0.16445199],
       [0.9904896 ],
       [0.01526064]], dtype=float32)

In [21]:
model.predict(["An excellent movie that I enjoyed a lot"])

array([[0.9904896]], dtype=float32)